# Generated by Django 4.2.10 on 2024-02-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_remove_userwishlist_user_userwishlist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwishlist',
            name='product',
        ),
        migrations.AddField(
            model_name='userwishlist',
            name='product',
            field=models.ManyToManyField(blank=True, to='adminapp.product'),
        ),
    ]
