# Generated by Django 4.2.13 on 2024-06-19 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_alter_customer_is_active_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
