# Generated by Django 4.2.13 on 2024-06-19 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_customertoken_usertoken_delete_extendedtoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customertoken',
            options={'verbose_name': 'CustomerToken', 'verbose_name_plural': 'CustomerTokens'},
        ),
        migrations.AlterModelOptions(
            name='usertoken',
            options={'verbose_name': 'UserToken', 'verbose_name_plural': 'UserTokens'},
        ),
        migrations.AlterModelManagers(
            name='customer',
            managers=[
            ],
        ),
    ]
