# Generated by Django 4.2.13 on 2024-06-19 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_alter_customertoken_options_alter_usertoken_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
