# Generated by Django 4.2.13 on 2024-06-19 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_alter_customer_options_alter_customer_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customer',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
