# Generated by Django 4.2.11 on 2024-04-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_status',
            field=models.BooleanField(default=False),
        ),
    ]
