# Generated by Django 4.2.11 on 2024-04-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_user_created_by_user_modified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='modified_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
