# Generated by Django 4.2.11 on 2024-04-04 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_blogpost_created_by_alter_blogpost_modified_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='likes',
        ),
    ]
