# Generated by Django 4.2.11 on 2024-04-04 11:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_blogpost_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='like',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
