# Generated by Django 4.2.11 on 2024-04-05 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_blogpost_user_alter_userotp_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='like',
        ),
    ]
