# Generated by Django 4.2.11 on 2024-04-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_blogpost_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='like',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
    ]
