# Generated by Django 4.2.11 on 2024-04-05 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_blogpost_like_blogpost_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='like',
        ),
    ]
