# Generated by Django 4.2.11 on 2024-04-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_alter_blogpost_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='like',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
