# Generated by Django 4.2.11 on 2024-04-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_remove_coupon_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='discount_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
