# Generated by Django 4.2.11 on 2024-04-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_coupon_discount_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_code',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
